development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: eazia_development

test:
  adapter: test

production:
  adapter: sidekiq
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: eazia_production
