development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: eazia_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") %>
  channel_prefix: eazia_production
